version: '3.8'

services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: capitas_parcial
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - capas

  app:
    build:
      context: .
      platform: linux/amd64           
    container_name: mi-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supportdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - capas

volumes:
  postgres_data:

networks:
  capas:
    driver: bridge